version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: "weekly"
    groups:
     all:
       patterns:
         - "*"
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    groups:
     all:
       patterns:
         - "*"
